import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "App Next.Js by GM",
  description: "Generated by create next app",
  image: "https://img.asmedia.epimg.net/resizer/v2/WOXKPV2C2NPMNDXYYM6VBC6VKQ.jpg?auth=cae554e7b5171ab44b35daad46b84c7011aaae6bc856db6a3ab17d4744876466&width=976&height=549&smart=true",
  type: "website",
  keywords: "Next.js, React,Prisma, Tailwind, PostgreSQL, API, CRUD, Web Development, Frontend, Backend, Full Stack, JavaScript, Web Application",
  authors: [{ name: "Gabriel Marzioli", url: "https://github.com/gabriel-marzioli" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="">
        <nav className=" flex  items-center p-4 min-w-screen bg-gray-800 text-white">
          <ul className="flex space-x-10 text-xl justify-center w-full">
            <li>
              <Link href="/" >
                Home
              </Link>
            </li>
            <li>
              <Link href="/ingresar" >
                Ingresar
              </Link>
            </li>
            <li>
              <Link href="/articulos" >
                Artículos
              </Link>
            </li>
            <li>
              <Link href="/posts" >
                Posts
              </Link>
            </li>

            <li>
              <Link href="/ingresarSAct" >
                Ingresar Server Actions
              </Link>
            </li>

            <li>
              <Link href="/editarParams" >
                Editar Params
              </Link>
            </li>

          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
